play_music:
  description: "Play music on a specified device"
  fields:
    device_name:
      description: "Name of the device to play music on"
      example: "Living Room Speaker"
    track_uri:
      description: "Spotify track URI"
      example: "spotify:track:3n3Ppam7vgaVa1iaRUc9Lp"

stop_music:
  description: "Stop music on a specified device"
  fields:
    device_name:
      description: "Name of the device to stop music on"
      example: "Living Room Speaker"
